  app:
    mail:
      host: ${SMTP_HOST:smtp.gmail.com}
      port: ${SMTP_PORT:587}
      username: ${SMTP_USER}
      password: ${SMTP_PASS}

  spring:
    application:
      name: back
    datasource:
      url: jdbc:postgresql://localhost:5432/coreonedb
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
    threads:
      virtual:
        enabled: true

    mail:
      host: ${app.mail.host}
      port: ${app.mail.port}
      username: ${app.mail.username}
      password: ${app.mail.password}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  logging:
    level:
      com.dev.fellipe.user_service: debug
      net.ttddyy.dsproxy.listener: debug
      org.springframework.security: debug

  server:
    port: 8080
    servlet:
      context-path: /
    error:
      include-stacktrace: never
      include-binding-errors: never
      include-message: always
      include-exception: false
    tomcat:
      threads:
        max: 20
